### ISSUE TITLE
Validator does not evaluate the whole schema

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/file-validator#19]
When I run the file-validator with the current assembler [schema](https://github.com/bioboxes/rfc/blob/master/container/short-read-assembler/input_schema.yaml)

and the input yaml:

``` YAML

---
version: 0.9.0
arguments:
    - wrong_fastq:
         - id: "pe"
           value: "example.fa"
           type: paired
```

It is accepted by the file validator even when the schema forbids this per definition. 
The schema itself is correct, you can test it:

http://jsonschemalint.com/draft4/
