### ISSUE TITLE
Validate mounted files

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/file-validator#6]
The input-validator should test if the files provided by the .yaml really exist.
The only type that can be tested is fastq.

**Comment by pbelmann** [comment]
@michaelbarton  sorry for the unclear description of this issue. I wanted to parse the yaml and check if the fasta is really mounted to the container:
Example:

``` YAML
---
version: 0.9.0
arguments:
   - fastq:
      - id: "pe" 
        value: "/test1/reads.fastq.gz"
        type: single
   - fragment_size:
      - id: "pe"
        value: 12324
```

Check if /bbx/input/test1/reads.fastq.gz really exists.
